# Alpha-3 Country Codes (maximum length = 3):
COUNTRIES = [
				('USA' , 'United States of America')
			]

# Alpha-3 Country Codes + Alpha-2 Territory Codes (maximum length = 6):
STATES_TERRITORIES_PROVINCES = [
								('USA-AL' , 'Alabama, USA'),
								('USA-AK' , 'Alaska, USA'),
								('USA-AS' , 'American Samoa, USA'),
								('USA-AZ' , 'Arizona, USA'),
								('USA-AR' , 'Arkansas, USA'),
								('USA-CA' , 'California, USA'),
								('USA-CO' , 'Colorado, USA'),
								('USA-CT' , 'Connecticut, USA'),
								('USA-DE' , 'Delaware, USA'),
								('USA-DC' , 'District of Columbia, USA'),
								('USA-FL' , 'Florida, USA'),
								('USA-GA' , 'Georgia, USA'),
								('USA-GU' , 'Guam, USA'),
								('USA-HI' , 'Hawaii, USA'),
								('USA-ID' , 'Idaho, USA'),
								('USA-IL' , 'Illinois, USA'),
								('USA-IN' , 'Indiana, USA'),
								('USA-IA' , 'Iowa, USA'),
								('USA-KS' , 'Kansas, USA'),
								('USA-KY' , 'Kentucky, USA'),
								('USA-LA' , 'Louisiana, USA'),
								('USA-ME' , 'Maine, USA'),
								('USA-MD' , 'Maryland, USA'),
								('USA-MA' , 'Massachusetts, USA'),
								('USA-MI' , 'Michigan, USA'),
								('USA-MN' , 'Minnesota, USA'),
								('USA-MS' , 'Mississippi, USA'),
								('USA-MO' , 'Missouri, USA'),
								('USA-MT' , 'Montana, USA'),
								('USA-NE' , 'Nebraska, USA'),
								('USA-NV' , 'Nevada, USA'),
								('USA-NH' , 'New Hampshire, USA'),
								('USA-NJ' , 'New Jersey, USA'),
								('USA-NM' , 'New Mexico, USA'),
								('USA-NY' , 'New York, USA'),
								('USA-NC' , 'North Carolina, USA'),
								('USA-ND' , 'North Dakota, USA'),
								('USA-MP' , 'Northern Mariana Islands, USA'),
								('USA-OH' , 'Ohio, USA'),
								('USA-OK' , 'Oklahoma, USA'),
								('USA-OR' , 'Oregon, USA'),
								('USA-PA' , 'Pennsylvania, USA'),
								('USA-PR' , 'Puerto Rico, USA'),
								('USA-RI' , 'Rhode Island, USA'),
								('USA-SC' , 'South Carolina, USA'),
								('USA-SD' , 'South Dakota, USA'),
								('USA-TN' , 'Tennessee, USA'),
								('USA-TX' , 'Texas, USA'),
								('USA-UT' , 'Utah, USA'),
								('USA-VT' , 'Vermont, USA'),
								('USA-VI' , 'Virgin Islands, USA'),
								('USA-VA' , 'Virginia, USA'),
								('USA-WA' , 'Washington, USA'),
								('USA-WV' , 'West Virginia, USA'),
								('USA-WI' , 'Wisconsin, USA'),
								('USA-WY' , 'Wyoming, USA')
							]
